// This file is generated by `cargo run -p hackline-proto --features specta --example wire_ts`.
// Do not edit by hand. The Rust source of truth lives in the
// `hackline-proto` crate. Regenerate after changing any wire type,
// and commit the result.
//
// Scope mirrors `tests/specta_snapshot.rs`: connection-lifecycle and
// event types. Envelope types carrying `serde_json::Value` payloads
// land in a follow-up that ships the `Value -> unknown` shim.

// Describes a running agent instance.
export type AgentInfo = {
	label: string | null,
	allowed_ports: number[],
};

/**
 *  Ack flowing device→gateway on
 *  `hackline/<zid>/msg/cmd-ack/<cmd_id>` after the device's handler
 *  finishes (or rejects) the command.
 */
export type CmdAck = {
	cmd_id: string,
	result: CmdResult,
	detail?: string | null,
};

// Outcome reported by the device-side cmd handler.
export type CmdResult = "accepted" | "rejected" | "failed" | "done";

/**
 *  Reply from the agent. If `ok` is true, the paired pub/sub channels
 *  are ready for bytes.
 */
export type ConnectAck = {
	request_id: string,
	ok: boolean,
	message: string | null,
};

/**
 *  Sent by the gateway as the payload of a Zenoh `get` on
 *  `hackline/<zid>/tcp/<port>/connect`.
 */
export type ConnectRequest = {
	// Ties gateway and agent log lines together.
	request_id: string,
	// Peer address for the agent's audit log.
	peer: string | null,
};

export type Event = { type: "device_online"; device_id: number } | { type: "device_offline"; device_id: number } | { type: "tunnel_opened"; tunnel_id: number } | { type: "tunnel_closed"; tunnel_id: number } | { type: "tunnel_connection"; tunnel_id: number; request_id: string };

// Five-level log severity. Lowercase string on the wire and in DB.
export type LogLevel = "trace" | "debug" | "info" | "warn" | "error";

// A validated Zenoh device identifier.
export type Zid = string;
